services:
  db:
    image: postgres:16-alpine
    container_name: nexpulse_db
    restart: always
    environment:
      POSTGRES_USER: nexpulseuser
      POSTGRES_PASSWORD: nexpulsepass
      POSTGRES_DB: nexpulsedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
