"""auto_migration_1777541097

Revision ID: 956a3f3e1935
Revises: c8c31ad871fc
Create Date: 2026-04-30 14:54:57.824260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956a3f3e1935'
down_revision: Union[str, None] = 'c8c31ad871fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('collect_demographics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'collect_demographics')
    # ### end Alembic commands ###
