"""auto_migration_1777537105

Revision ID: c5f8f3247d79
Revises: d8a70df92924
Create Date: 2026-04-30 13:48:25.969682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f8f3247d79'
down_revision: Union[str, None] = 'd8a70df92924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('client_ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'client_ip')
    # ### end Alembic commands ###
