"""auto_migration_1777535376

Revision ID: d8a70df92924
Revises: 325ee5f86faf
Create Date: 2026-04-30 13:19:36.441134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a70df92924'
down_revision: Union[str, None] = '325ee5f86faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('survey_responses', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('survey_responses', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('survey_responses', sa.Column('occupation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'occupation')
    op.drop_column('survey_responses', 'city')
    op.drop_column('survey_responses', 'gender')
    op.drop_column('survey_responses', 'age')
    # ### end Alembic commands ###
